Remove flashmessenger view helper
laminas/laminas-view pull request #135
Opened 2022-02-01 16:06 UTC by gsteel

### Description

Rebases and resolves #47

2022-02-01 16:11 UTC, Ocramius approved these changes
Nice, didn't even know it was split out!

2022-02-01 16:14 UTC, gsteel commented
7.4 on lowest looks stuck - can you re-trigger please @Ocramius

2022-03-23 14:59 UTC, Ocramius commented
GHA didn't start at all here :thinking:

2022-03-23 15:00 UTC, Ocramius commented
Welp, it's broken again: https://www.githubstatus.com/

2022-03-23 15:01 UTC, gsteel commented
Not again 🙄

2022-03-23 17:20 UTC, Ocramius commented
I think pushing an empty commit would give us feedback here - really sorry to push it on contributors, but can't do it from here ATM :|

2022-03-23 17:21 UTC, gsteel commented
> I think pushing an empty commit would give us feedback here - really sorry to push it on contributors, but can't do it from here ATM :|

I think GHA is still down isn't it?

2022-03-23 17:23 UTC, Ocramius commented
Seems to be working/picking up stuff - the hook system was completely broken though

2022-03-23 17:45 UTC, gsteel commented
Appears to have gone green despite the UI not showing the checks: https://github.com/laminas/laminas-view/actions/runs/2029729860

2022-03-23 17:50 UTC, Ocramius requested changes

2022-03-23 17:50 UTC, Ocramius commented on composer.json
> -        "laminas/laminas-escaper": "^2.5",
Is escaper supposed to be gone?

2022-03-23 17:55 UTC, gsteel commented on composer.json
> -        "laminas/laminas-escaper": "^2.5",
It's not gone, it was moved to `require` in 2.x but a merge popped it back in `require-dev` too, so I removed it from `require-dev` in this pull to clean up. I must have missed this resolving conflicts earlier today.

2022-03-24 01:07 UTC, Ocramius approved these changes
LGTM 🚢

2022-03-24 01:07 UTC, merged

2022-03-24 01:07 UTC, Ocramius commented
Thanks @gsteel!