Initial RFC for Doctype Replacement Helper
laminas/laminas-view pull request #142
Opened 2022-02-19 19:49 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | yes
| RFC           | yes

### Description

I think the doctype helper could do with a lot of simplification and the added file `DoctypeV3` is what I think the helper should look like:

- Construct expects a single string argument that identifies a doctype declaration
- There is a method that allows you to retrieve the configured doctype, or any other known doctype by its id
- Casting to a string yields the configured doctype
- There are a few other methods that can tell you if the configured or the given doctype is Html5, RDFa or or Xhtml.

Removed functionality:

- Custom DocTypes are gone _(Why would you need one? and if you do, why, not just write your own helper or hard-code it in the layout?)_
- The static registry thing has gone
- Run-time modification of the doctype is gone.

If something like this can be agreed in principal, I'll rename/replace the existing helper and factory to suit and write/update all the tests broken by the change.

I'll also create a pull for the 2.x series with all the deprecations.

2022-02-19 21:15 UTC, Ocramius requested changes

2022-02-19 21:15 UTC, Ocramius commented on src/Helper/DoctypeV3.php
> +    /** @return non-empty-string */
IMO `key-of<self::$docTypeDefinitions>`

2022-02-19 21:15 UTC, Ocramius commented on src/Helper/DoctypeV3.php
> +    private static $docTypeDefinitions = [
Can be a constant

2022-02-19 21:15 UTC, Ocramius commented on src/Helper/DoctypeV3.php
> +    public function isXhtml(?string $doctypeId = null): bool
Also here, let's restrict these input types as much as possible

2022-02-19 22:02 UTC, gsteel commented on src/Helper/DoctypeV3.php
> +    /** @return non-empty-string */
Nice - Didn't know that!

2025-05-05 16:20 UTC, Ocramius approved these changes

2025-05-05 16:20 UTC, Ocramius commented on src/Helper/Doctype.php
> +     * @param DoctypeID|string|null $doctypeId
Thr `|string` kinda kills all type safety introduced here though

2025-05-05 16:24 UTC, gsteel commented on src/Helper/Doctype.php
> +     * @param DoctypeID|string|null $doctypeId
Yes - this was mainly so that the defensive check/exception was worth doing. I figured the check was worth retaining because of less precise inputs from a view script context.

Theoretically, no-one will interact with that method anyhow, unless they are using the helper as a lookup table, and it'll crash for invalid input.

2025-05-05 16:26 UTC, gsteel commented on src/Helper/Doctype.php
> +     * @param DoctypeID|string|null $doctypeId
Am hoping that I can ship a Psalm plugin and collector (or whatever they're called) so we can get SA on .phtml files BTW

2025-05-05 21:54 UTC, froschdesign requested changes

2025-05-05 21:54 UTC, froschdesign commented on docs/book/v3/helpers/doctype.md
> +$helper = new Doctype(Doctype::HTML5);
HTML5 is the default doctype therefore it should be omitted.
A second example with a different doctype would be good.

2025-05-05 21:54 UTC, froschdesign commented on docs/book/v3/helpers/doctype.md
> +!NOTE The default doctype is HTML 5 when no configuration is specified.
The syntax is wrong but I would explain this with a second example, see above.

> ## Basic Usage
> 
> Start the admonition with one of the types in capital letters followed by a
> colon.
> The type corresponds with a specific style.
> The type should be followed by the content of the admonition.
> 
> ```markdown
> NOTE: An example of a note.
> ```
>
> ## Type of Admonitions
> 
> | Title / Topic             | Type    |
> |---------------------------|---------|
> | New Feature               | TIP     |
> | Deprecation Warning       | CAUTION |
> | Installation Requirements | MISSING |
> | General Notes             | NOTE    |
> | Security Warning          | WARNING |

2025-05-06 07:19 UTC, froschdesign approved these changes

2025-05-06 08:21 UTC, merged