PHP 8.3 support added
laminas/laminas-view pull request #219
Opened 2023-10-10 10:37 UTC by glo71317

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

2023-10-17 15:24 UTC, gsteel requested changes
In order to run tests on 8.3, you'll need to ignore platform requirements for 8.3 in `.laminas-ci.json` too

2023-10-18 07:24 UTC, glo71317 commented
> In order to run tests on 8.3, you'll need to ignore platform requirements for 8.3 in `.laminas-ci.json` too

I have updated

2023-10-18 09:56 UTC, gsteel requested changes

2023-10-18 09:56 UTC, gsteel commented on .laminas-ci.json
> +        "8.3": false
This needs to be `true` in order to actually ignore platform requirements:

https://github.com/laminas/laminas-ci-matrix-action?tab=readme-ov-file#configuration

2023-11-03 13:49 UTC, gsteel commented
Thanks @glo71317 but this has been handled in #226

2023-11-03 13:49 UTC, closed without merging