Psalm integration
laminas/laminas-view pull request #80
Opened 2021-10-09 15:51 UTC by konarshankar07

Signed-off-by: Shankar Konar <konar.shankar2013@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

Psalm integration added

2021-10-10 14:30 UTC, boesing commented
Thanks, @konarshankar07 
We have to add the new CI pipeline to this package before we can merge this.
Anyways, thanks for your efforts! This will still count for hacktoberfest due to the `hacktoberfest-accepted` label 👍🏼

2021-10-11 05:11 UTC, konarshankar07 commented
Hello @boesing 
If you provide the steps to add the new CI pipeline then I can implement that too. I guess you are going to implement the github actions for the CI pipeline
Thanks

2021-10-11 06:05 UTC, froschdesign commented
@boesing 
The CI workflow is already there, see at the 2.12.x branch:

> This branch is 30 commits ahead, 1 commit behind 3.0.x.

https://github.com/laminas/laminas-view/blob/2.12.x/.github/workflows/continuous-integration.yml

Some cleanup is needed: https://github.com/laminas/laminas-view/issues/71

2021-10-11 06:06 UTC, froschdesign commented
@konarshankar07 
Please use the 2.12.x as target branch for this pull request. Thanks!

2021-10-11 12:36 UTC, Ocramius commented
Seems like our own deprecations are at fault with the failure here :|

2021-10-11 17:03 UTC, boesing commented
> Seems like our own deprecations are at fault with the failure here :|

actually this is due to the phpunit change regarding `deprecationsToExceptions`.
The Tests which fail are to ensure the the deprecation will be triggered (just not that well implemented) and these now fail in latest phpunit.

2021-10-11 17:40 UTC, konarshankar07 commented
@boesing @Ocramius 
Yes, I have fixed this here https://github.com/laminas/laminas-crypt/pull/14/commits/034976ef0b3097ac88df8487f7cffb0d5a531721 already and will do the same

2021-10-12 07:03 UTC, boesing requested changes
Overall, LGTM - just a few adjustments so we can avoid suppressions.

Another thing is, that it seems that we only have less than 20 errors in this projects. Would you mind fixing these so we end up having 100% typed code rather than suppressing these few errors via baseline? That would really be appreciated 🙏🏼

2021-10-12 07:03 UTC, boesing commented on .psalm.xml.dist
> +    <issueHandlers>
if you add `psalm/plugin-phpunit` and enable it with `vendor/bin/psalm-plugin`, you should be able to remove these issue handlers.

2021-10-12 07:03 UTC, boesing commented on .psalm.xml.dist
> +    totallyTyped="true"
`totallyTyped=true` is deprecated in favor of `errorLevel=1`.

2021-10-12 08:22 UTC, konarshankar07 commented on .psalm.xml.dist
> +    totallyTyped="true"
If I run the pslam with errorLevel=1 then I'm getting 4599 errors. Do we need to fix all the errors? or Am I missing something?
![image](https://user-images.githubusercontent.com/39480008/136919345-03e9fc8e-7e2a-4954-b745-b3101d36f3a2.png)
Thanks

2021-10-12 18:22 UTC, weierophinney commented on .psalm.xml.dist
> +    totallyTyped="true"
The idea is to establish an initial baseline; see #56 as it details this.

I've done that and pushed changes to the branch at this time.

2021-10-12 18:30 UTC, merged