Re-enable skipped tests and improve type coverage
laminas/laminas-view pull request #89
Opened 2021-10-13 23:28 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | maybe
| QA            | yes

### Description

Mostly just QA re-enabling tests and cleaning up modified tests for CS and psalm.

Potential BC break is changing ExceptionInterface to extend from Throwable - if this _is_ a BC break, I can revert and update baseline.

2021-10-13 23:34 UTC, gsteel commented
Tests are failing on 8.1 because Paginator needs to be compatible with 8.1

2021-10-14 05:45 UTC, froschdesign commented
@gsteel 
> Tests are failing on 8.1 because Paginator needs to be compatible with 8.1

There are already some pollyfills:

https://github.com/laminas/laminas-view/tree/2.14.x/polyfill

Maybe the problem can be solved this way _for the moment_.

(I will create issue reports in the related component issue trackers to remove the pollyfills with an update.)

2021-10-14 06:13 UTC, froschdesign commented
@gsteel 
I found another problem:

https://github.com/laminas/laminas-view/blob/7ba573a745c16b4359fac558b4ef8af7426943a8/test/Helper/LayoutTest.php#L17-L34

If you could take a look at it, I would be very grateful.

2021-10-14 09:19 UTC, gsteel commented
> @gsteel
> 
> > Tests are failing on 8.1 because Paginator needs to be compatible with 8.1
> 
> There are already some pollyfills:
> 
> https://github.com/laminas/laminas-view/tree/2.14.x/polyfill
> 
> Maybe the problem can be solved this way _for the moment_.
> 
> (I will create issue reports in the related component issue trackers to remove the pollyfills with an update.)

Hi @froschdesign - I've added these polyfills and addressed the uninitialised props in Layout test

2021-10-14 09:20 UTC, froschdesign commented on src/Exception/ExceptionInterface.php
> +interface ExceptionInterface extends Throwable
@Ocramius @boesing 
> Potential BC break is changing ExceptionInterface to extend from Throwable - if this is a BC break, I can revert and update baseline.

Any comments on this change?

2021-10-14 09:22 UTC, froschdesign commented
@gsteel 
> I've added these polyfills and addressed the uninitialised props in Layout test

I have already seen that. Great and thank you! 👍 

(I have the issue reports for the components on my list.)

2021-10-14 13:48 UTC, Ocramius commented on src/Exception/ExceptionInterface.php
> +interface ExceptionInterface extends Throwable
Potentially a BC break, but then `ExceptionInterface` is not supposed to be relied upon when implementing things downstream, but rather as a marker interface.

IMO acceptable, and I'm prepared to tell downstream consumers why they were wrong upfront, should there be problems :-)

2021-10-14 13:49 UTC, Ocramius requested changes

2021-10-14 13:49 UTC, Ocramius commented on polyfill/Paginator/ArrayAdapter.php
> + * @todo Remove when laminas-paginator has a release targeting PHP 8.1.
Can we make this `@internal` here?

2021-10-14 13:49 UTC, Ocramius commented on polyfill/Paginator/ArrayAdapter.php
> +namespace Laminas\Paginator\Adapter;
We should `export-ignore` the `polyfill/` directory

2021-10-14 13:57 UTC, Ocramius approved these changes
LGTM :+1:

2021-10-14 14:02 UTC, froschdesign commented on polyfill/Paginator/ArrayAdapter.php
> +namespace Laminas\Paginator\Adapter;
@Ocramius 
But this means that in other environments laminas-view does not work with the paginator and PHP 8.1.
I am a bit surprised because it was not excluded before.

2021-10-14 14:07 UTC, Ocramius commented
Oooof, there's no `2.15.x` :| 

This sort of stuff should really be in a minor, but `laminas/automatic-releases` (correctly) didn't create `2.15.x`, because `3.0.x` already exists.

2021-10-14 14:09 UTC, Ocramius commented on polyfill/Paginator/ArrayAdapter.php
> +namespace Laminas\Paginator\Adapter;
@froschdesign aren't the `polyfill/` classes just for test use? They were only loaded in `autoload-dev`

2021-10-14 14:10 UTC, froschdesign commented on polyfill/Paginator/ArrayAdapter.php
> +namespace Laminas\Paginator\Adapter;
You're absolutely right, of course!

2021-12-17 11:25 UTC, merged

2021-12-17 11:25 UTC, Ocramius commented
Thanks @gsteel!